// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kernel_matrix_cpp
arma::mat kernel_matrix_cpp(const arma::mat& X, const arma::mat& Z, const std::string& kernel, double gamma, int degree, double coef0);
RcppExport SEXP _twinsvm_kernel_matrix_cpp(SEXP XSEXP, SEXP ZSEXP, SEXP kernelSEXP, SEXP gammaSEXP, SEXP degreeSEXP, SEXP coef0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_matrix_cpp(X, Z, kernel, gamma, degree, coef0));
    return rcpp_result_gen;
END_RCPP
}
// smo_cpp
Rcpp::List smo_cpp(const arma::mat& X, const arma::vec& y, double cost, const std::string& kernel, double gamma, int degree, double coef0, double tol, int max_passes, int max_iter);
RcppExport SEXP _twinsvm_smo_cpp(SEXP XSEXP, SEXP ySEXP, SEXP costSEXP, SEXP kernelSEXP, SEXP gammaSEXP, SEXP degreeSEXP, SEXP coef0SEXP, SEXP tolSEXP, SEXP max_passesSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type cost(costSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_passes(max_passesSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(smo_cpp(X, y, cost, kernel, gamma, degree, coef0, tol, max_passes, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// qptsvm_linear_cpp
Rcpp::List qptsvm_linear_cpp(const arma::mat& A, const arma::mat& B, double c1, double c2, double eps, int max_iter, double tol);
RcppExport SEXP _twinsvm_qptsvm_linear_cpp(SEXP ASEXP, SEXP BSEXP, SEXP c1SEXP, SEXP c2SEXP, SEXP epsSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(qptsvm_linear_cpp(A, B, c1, c2, eps, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// qptsvm_kernel_cpp
Rcpp::List qptsvm_kernel_cpp(const arma::mat& A, const arma::mat& B, const arma::mat& C, const std::string& kernel, double gamma, int degree, double coef0, double c1, double c2, double eps, int max_iter, double tol);
RcppExport SEXP _twinsvm_qptsvm_kernel_cpp(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP kernelSEXP, SEXP gammaSEXP, SEXP degreeSEXP, SEXP coef0SEXP, SEXP c1SEXP, SEXP c2SEXP, SEXP epsSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(qptsvm_kernel_cpp(A, B, C, kernel, gamma, degree, coef0, c1, c2, eps, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// lstsvm_linear_cpp
Rcpp::List lstsvm_linear_cpp(const arma::mat& A, const arma::mat& B, double c1, double c2, double eps);
RcppExport SEXP _twinsvm_lstsvm_linear_cpp(SEXP ASEXP, SEXP BSEXP, SEXP c1SEXP, SEXP c2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(lstsvm_linear_cpp(A, B, c1, c2, eps));
    return rcpp_result_gen;
END_RCPP
}
// lstsvm_kernel_cpp
Rcpp::List lstsvm_kernel_cpp(const arma::mat& A, const arma::mat& B, const arma::mat& C, const std::string& kernel, double gamma, int degree, double coef0, double c1, double c2, double eps);
RcppExport SEXP _twinsvm_lstsvm_kernel_cpp(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP kernelSEXP, SEXP gammaSEXP, SEXP degreeSEXP, SEXP coef0SEXP, SEXP c1SEXP, SEXP c2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(lstsvm_kernel_cpp(A, B, C, kernel, gamma, degree, coef0, c1, c2, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_twinsvm_kernel_matrix_cpp", (DL_FUNC) &_twinsvm_kernel_matrix_cpp, 6},
    {"_twinsvm_smo_cpp", (DL_FUNC) &_twinsvm_smo_cpp, 10},
    {"_twinsvm_qptsvm_linear_cpp", (DL_FUNC) &_twinsvm_qptsvm_linear_cpp, 7},
    {"_twinsvm_qptsvm_kernel_cpp", (DL_FUNC) &_twinsvm_qptsvm_kernel_cpp, 12},
    {"_twinsvm_lstsvm_linear_cpp", (DL_FUNC) &_twinsvm_lstsvm_linear_cpp, 5},
    {"_twinsvm_lstsvm_kernel_cpp", (DL_FUNC) &_twinsvm_lstsvm_kernel_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_twinsvm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
