# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernel_matrix_cpp <- function(X, Z, kernel, gamma, degree, coef0) {
    .Call(`_twinsvm_kernel_matrix_cpp`, X, Z, kernel, gamma, degree, coef0)
}

smo_cpp <- function(X, y, cost, kernel, gamma, degree, coef0, tol, max_passes, max_iter) {
    .Call(`_twinsvm_smo_cpp`, X, y, cost, kernel, gamma, degree, coef0, tol, max_passes, max_iter)
}

qptsvm_linear_cpp <- function(A, B, c1, c2, eps, max_iter = 10000L, tol = 1e-6) {
    .Call(`_twinsvm_qptsvm_linear_cpp`, A, B, c1, c2, eps, max_iter, tol)
}

qptsvm_kernel_cpp <- function(A, B, C, kernel, gamma, degree, coef0, c1, c2, eps, max_iter = 10000L, tol = 1e-6) {
    .Call(`_twinsvm_qptsvm_kernel_cpp`, A, B, C, kernel, gamma, degree, coef0, c1, c2, eps, max_iter, tol)
}

lstsvm_linear_cpp <- function(A, B, c1, c2, eps) {
    .Call(`_twinsvm_lstsvm_linear_cpp`, A, B, c1, c2, eps)
}

lstsvm_kernel_cpp <- function(A, B, C, kernel, gamma, degree, coef0, c1, c2, eps) {
    .Call(`_twinsvm_lstsvm_kernel_cpp`, A, B, C, kernel, gamma, degree, coef0, c1, c2, eps)
}

